#!/usr/bin/env python
#!-*- coding: utf8 -*-
from node import Node
from edge import Edge


def main():
    lesaoNode = Node("Possui lesão ?")
    aguaSoloNode = Node("Prefiro atividades em..")
    radicalNode = Node("Esportes radicais..")
    contatoNode = Node("Prefiro esportes..")
    contatoSemLesaoNode = Node("Prefiro esportes..")
    objetivoNode = Node("Meu foco é..")
    objetivoSemLesaoNode = Node("Meu foco é..")
    objetivoCorporalNode = Node("Gostaria de..")
    pesMaosNode = Node("Prefiro trabalhar com..")
    equipeNode = Node("Gosto de atividades em..")
    equipeSemLesaoNode = Node("Gosto de atividades em..")

    # LEAFS
    surfeLeaf = Node("Surfe")
    natacaoLeaf = Node("Natação")
    hidroLeaf = Node("Hidroginástica")
    dancaLeaf = Node("Dança de Salão")
    iogaLeaf = Node("Ioga")
    rugbyLeaf = Node("Rugby")
    futebolLeaf = Node("Futebol")
    kungFuLeaf = Node("KungFu")
    boxeLeaf = Node("Boxe")
    voleiLeaf = Node("Volei")
    tenisLeaf = Node("Tênis")
    musculacaoLeaf = Node("Musculação")
    ciclismoLeaf = Node("Ciclismo")

    lesaoSimEdge = Edge("Sim", aguaSoloNode)
    lesaoNaoEdge = Edge("Não", contatoSemLesaoNode)
    aguaSoloAguaEdge = Edge("Água", radicalNode)
    aguaSoloSoloEdge = Edge("Solo", contatoNode)
    radicalSimEdge = Edge("Sim", surfeLeaf)
    radicalNaoEdge = Edge("Não", objetivoNode)
    objetivoCompetirEdge = Edge("Competir", natacaoLeaf)
    objetivoSaudeEdge = Edge("Saúde", hidroLeaf)
    objetivoSemLesaoCompetirEdge = Edge("Competir", equipeSemLesaoNode)
    objetivoSemLesaoSaudeEdge = Edge("Saúde", objetivoCorporalNode)
    contatoSimEdge = Edge("Com contato", iogaLeaf)
    contatoNaoEdge = Edge("Sem contato", dancaLeaf)
    contatoSemLesaoSimEdge = Edge("Com contato", pesMaosNode)
    pesMaosPesEdge = Edge("Pes", futebolLeaf)
    pesMaosMaosEdge = Edge("Mãos", boxeLeaf)
    pesMaosAmbosEdge = Edge("Ambos", equipeNode)
    equipeEquipeEdge = Edge("Equipe", rugbyLeaf)
    equipeSozinhoEdge = Edge("Sozinho", kungFuLeaf)
    contatoSemLesaoNaoEdge = Edge("Sem contato", objetivoSemLesaoNode)
    equipeSemLesaoEquipeEdge = Edge("Equipe", voleiLeaf)
    equipeSemLesaoSozinhoEdge = Edge("Sozinho", tenisLeaf)
    objetivoCorporalTonificarEdge = Edge("Tonificar", musculacaoLeaf)
    objetivoCorporalEmagrecerEdge = Edge("Emagrecer", ciclismoLeaf)

    lesaoNode.addEdge(lesaoNaoEdge)
    lesaoNode.addEdge(lesaoSimEdge)
    contatoSemLesaoNode.addEdge(contatoSemLesaoNaoEdge)
    contatoSemLesaoNode.addEdge(contatoSemLesaoSimEdge)
    pesMaosNode.addEdge(pesMaosMaosEdge)
    pesMaosNode.addEdge(pesMaosPesEdge)
    pesMaosNode.addEdge(pesMaosAmbosEdge)
    aguaSoloNode.addEdge(aguaSoloAguaEdge)
    aguaSoloNode.addEdge(aguaSoloSoloEdge)
    radicalNode.addEdge(radicalSimEdge)
    radicalNode.addEdge(radicalNaoEdge)
    objetivoNode.addEdge(objetivoCompetirEdge)
    objetivoNode.addEdge(objetivoSaudeEdge)
    contatoNode.addEdge(contatoSimEdge)
    contatoNode.addEdge(contatoNaoEdge)
    equipeNode.addEdge(equipeSozinhoEdge)
    equipeNode.addEdge(equipeEquipeEdge)
    equipeSemLesaoNode.addEdge(equipeSemLesaoSozinhoEdge)
    equipeSemLesaoNode.addEdge(equipeSemLesaoEquipeEdge)
    objetivoCorporalNode.addEdge(objetivoCorporalEmagrecerEdge)
    objetivoCorporalNode.addEdge(objetivoCorporalTonificarEdge)
    objetivoSemLesaoNode.addEdge(objetivoSemLesaoCompetirEdge)
    objetivoSemLesaoNode.addEdge(objetivoSemLesaoSaudeEdge)

    selectedNode = lesaoNode
    while (selectedNode.hasEdges()):
        selectedNode = selectedNode.ask()
    print "O esporte mais indicado para você é: " + str(selectedNode)
